client_config_backend: file
client_config:
    client_id: 813792313796-t6ap43hta1v4814n1au5pd9r5vaqgolr.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive